
GET http://localhost:{{port}}/api/user/me HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJwYXdpeCIsImlhdCI6MTcwMTUyOTA0OSwiZXhwIjoxNzAxNTI5MzQ5fQ.yBq9tq0g03rOxco0DraNLVRGZcUUjzdGNHgAUNoQJmk